[package]
authors = ["Jacob Brown <kardeiz@gmail.com>", "Krzysztof Saczuk <me@krzysztofsaczuk.pl>"]
edition = "2021"
name = "serde_tuple"
version = "1.1.0"
description = "De/serialize structs with named fields as array of values"
license = "MIT"
repository = "https://github.com/kardeiz/serde_tuple"
readme = "README.md"

[dependencies]
serde_tuple_macros = { version = "1.0.1", path = "./serde_tuple_macros" }
serde = { version = "1", features = ["derive"], default-features = false}

[dev-dependencies]
serde_json = "1.0.37"
